name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build

    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: [1.19.x]

    runs-on: ${{ matrix.platform }}
      
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: make build

    - name: Test
      run: make unit

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: 'latest'
